import { Router, Request, Response } from "express"
import pool from "../db" //pool allows backend code to talk to postgres and run SQL queries 

//create router instance 
const readingsRouter = Router()

//different kinds of routes: 
//get - fetches data, never modifies anything  
//post - creates a new record 
//put - updates an existing record (replaces the whole record)
//patch -updates an existing record (only updates specific fields) 
//delete - deletes a record 

//notes: 
//1. res is the response object, its what you send back to whoever made the request (in this case the react frontend)
//2. .json() sends data back as a json format 
//3. when something goes wrong in a try block JS automatically creates an error obkect describing what went wrong nd passes it to catch. contains error.message so we know what went wrong

//create routes 

//official name: GET request handler. this received the HTTP GET request fro the front end and sends out a response  
readingsRouter.get('/', async (req: Request, res: Response) => { // '/' is the route path, means the root of whatever path the router is mounted on 
  try {
    const dbResponse = await pool.query(`
      SELECT * 
      FROM readings
      ORDER BY reading_date DESC; 
      `)
    const readingData = dbResponse.rows
    res.status(200)
      .json(readingData)
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error' //checks if error is an error object, if it is we can access the error message, if not itll say 'Unknown error' since we dont know what was thrown. typescript doesn't know what's thrown, anything can eb thrown so we gotta make sure it's an error object
    res.status(500) //status(500) means server error 
      .json({ error: message }) //{ error } shorthand for { error: error }
  }
})

readingsRouter.post('/', async (req: Request, res: Response) => {
  try {
    const { reading_date, reading_topic, spread_type, notes, interpretation } = req.body //destructure request object 
    const dbResponse = await pool.query(`
      INSERT INTO readings (reading_date, reading_topic, spread_type, notes, interpretation)
      VALUES ($1, $2, $3, $4, $5)
      RETURNING *;`, 
      [reading_date, reading_topic, spread_type, notes, interpretation]
    ) //RETURNING * tells pg to send back the newly created row after inserting it including the autogenerated info  
    const newReading = dbResponse.rows[0] //result is response from pg to backend, res is response from backend to frontend 
    res.status(200) //set status code to 201 meaning new record was successfully created
      .json(newReading) //send response back in json 
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unkown error'
    res.status(500)
      .json({ error: message })
  }
})

readingsRouter.patch('/:readingId', async (req: Request, res: Response) => { //':' marks a URL parameter, allows us to destructure from req.params
  try {
    const { readingId } = req.params
    const { reading_date, reading_topic, spread_type, notes, interpretation } = req.body 

    const dbResponse = await pool.query(`
      UPDATE readings 
      SET reading_date = $1, reading_topic = $2, spread_type = $3, notes = $4, interpretation=$5
      WHERE id = $6
      RETURNING *;`, 
      [reading_date, reading_topic, spread_type, notes, interpretation, readingId]
    )
    const updatedReading = dbResponse.rows[0]
    res.status(201)
      .json(updatedReading)
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error'
    res.status(500)
      .json({ error: message })
  }
})

readingsRouter.delete('/:readingId', async (req: Request, res: Response) => {
  try {
    const { readingId } = req.params 
    const dbResponse = await pool.query(`
      DELETE FROM readings 
      WHERE id = $1
      RETURNING *;`, 
      [readingId]
    )
    const deletedReading = dbResponse.rows[0] 
    res.status(200)
      .json(deletedReading)
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error'
    res.status(500)
      .json({ error: message })
  }
})

export default readingsRouter 