import { Router, Request, Response } from "express";
import interpretReading from "../services/geminiService";
import pool from "../db"; //pool allows backend code to talk to postgres and run SQL queries

//create router instance
const readingsRouter = Router();

//different kinds of routes:
//get - fetches data, never modifies anything
//post - creates a new record
//put - updates an existing record (replaces the whole record)
//patch - updates an existing record (only updates specific fields)
//delete - deletes a record

//notes:
//1. res is the response object, its what you send back to whoever made the request (in this case the react frontend)
//2. .json() sends data back as a json format
//3. when something goes wrong in a try block JS automatically creates an error obkect describing what went wrong nd passes it to catch. contains error.message so we know what went wrong

//create routes

//official name: GET request handler. this received the HTTP GET request fro the front end and sends out a response
readingsRouter.get("/", async (req: Request, res: Response) => {
  // '/' is the route path, means the root of whatever path the router is mounted on
  try {
    const dbResponse = await pool.query(`
      SELECT * 
      FROM readings
      ORDER BY reading_date DESC; 
      `);
    const readingData = dbResponse.rows;
    res.status(200).json(readingData);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error"; //checks if error is an error object, if it is we can access the error message, if not itll say 'Unknown error' since we dont know what was thrown. typescript doesn't know what's thrown, anything can eb thrown so we gotta make sure it's an error object
    res
      .status(500) //status(500) means server error
      .json({ error: message }); //{ error } shorthand for { error: error }
  }
});

readingsRouter.get("/:readingId", async (req: Request, res: Response) => {
  try {
    const { readingId } = req.params;
    const dbResponse = await pool.query(
      `SELECT * 
        FROM readings 
        WHERE id = $1`,
      [readingId],
    );
    const readingData = dbResponse.rows[0];
    res.status(200).json(readingData);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown Error";
    res.status(500).json({ error: message });
  }
});

readingsRouter.get("/user/:userId", async (req: Request, res: Response) => {
  try {
    const { userId } = req.params;
    const dbResponse = await pool.query(
      `SELECT readings.*, 
          JSON_AGG(cards.card_name ORDER BY cards.position_order) AS card_names
       FROM readings 
       LEFT JOIN cards ON cards.reading_id = readings.id 
       WHERE readings.user_id = $1
       GROUP BY readings.id
       ORDER BY readings.reading_date DESC; 
       `,
      [userId],
    );

    const readingsData = dbResponse.rows;
    res.status(200).json(readingsData);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    res.status(500).json({ error: message });
  }
});

readingsRouter.post("/", async (req: Request, res: Response) => {
  try {
    const {
      user_id,
      reading_date,
      reading_topic,
      spread_type,
      notes,
      user_interpretation,
    } = req.body; //destructure request object
    const dbResponse = await pool.query(
      `
      INSERT INTO readings (user_id, reading_date, reading_topic, spread_type, notes, user_interpretation)
      VALUES ($1, $2, $3, $4, $5, $6)
      RETURNING *;`,
      [
        user_id,
        reading_date,
        reading_topic,
        spread_type,
        notes,
        user_interpretation,
      ],
    ); //RETURNING * tells pg to send back the newly created row after inserting it including the autogenerated info
    const newReading = dbResponse.rows[0]; //result is response from pg to backend, res is response from backend to frontend
    res
      .status(201) //set status code to 201 meaning new record was successfully created
      .json(newReading); //send response back in json
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    res.status(500).json({ error: message });
  }
});

readingsRouter.post(
  "/:readingId/interpret",
  async (req: Request, res: Response) => {
    try {
      const { readingId } = req.params;
      const readingDbResponse = await pool.query(
        `
      SELECT * 
      FROM readings 
      WHERE id = $1`,
        [readingId],
      );
      const readingData = readingDbResponse.rows[0];

      const cardDbResponse = await pool.query(
        `
        SELECT * 
        FROM cards 
        WHERE reading_id = $1`,
        [readingId],
      );

      const cardData = cardDbResponse.rows;

      const prompt = `
        Interpret the following tarot reading given a topic, spread, cards, and notes inputted by the user. For each card you will be given the card name, the position order in the spread, and the name associated with the position order. Use all of this data to deliver a concise interpretation of the reading for the reader. Structure the interpretation in the following format: ###Overall Reading Summary 4 sentences max; ###Card by Card Analysis 3 sentences max for each card. Put the returned text in Markdown format: Overall Reading Summary and Card by Card analysis are ### Heading; Card names are are **bold text**. Include a colon ':' after specific card names. Do not bullet the card by card analysis results. Do not include introductory text such as "Here is an interpretation of your tarot reading.". Do not include the spread or reading topic, the user already knows this. 
        <reading_topic>${readingData.reading_topic}</reading_topic>
        <reading_spread>${readingData.spread_type}</reading_spread>
        <cards>${cardData
          .map((card) => {
            return `
            <card_name>${card.card_name}</card_name>
            <position_order>${card.position_order}</position_order>
            <position_name>${card.position_name}</position_name>
            `;
          })
          .join("")}</cards>
        <user_notes>${readingData.notes}</user_notes>
      `;

      const interpretation = await interpretReading(prompt);
      res.status(200).json(interpretation);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown Error";
      res.status(500).json({ error: message });
    }
  },
);

//update reading (notes and user interpretation)
readingsRouter.patch("/:readingId", async (req: Request, res: Response) => {
  //':' marks a URL parameter, allows us to destructure from req.params
  try {
    const { readingId } = req.params;
    const { notes, user_interpretation } = req.body;

    const dbResponse = await pool.query(
      `
      UPDATE readings 
      SET notes = $1, user_interpretation=$2
      WHERE id = $3
      RETURNING *;`,
      [notes, user_interpretation, readingId],
    );
    const updatedReading = dbResponse.rows[0];
    res.status(201).json(updatedReading);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    res.status(500).json({ error: message });
  }
});

//save & update ai interpretation
readingsRouter.patch(
  "/:readingId/ai-interpretation",
  async (req: Request, res: Response) => {
    try {
      console.log(req.body);
      const { readingId } = req.params;
      const { ai_interpretation } = req.body;

      const dbResponse = await pool.query(
        `UPDATE readings
        SET ai_interpretation = $1
        WHERE id = $2
        RETURNING *;`,
        [ai_interpretation, readingId],
      );

      const updatedReading = dbResponse.rows[0];
      res.status(201).json(updatedReading);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown Error";
      res.status(500).json({ error: message });
    }
  },
);

readingsRouter.delete("/:readingId", async (req: Request, res: Response) => {
  try {
    const { readingId } = req.params;
    const dbResponse = await pool.query(
      `
      DELETE FROM readings 
      WHERE id = $1
      RETURNING *;`,
      [readingId],
    );
    const deletedReading = dbResponse.rows[0];
    res.status(200).json(deletedReading);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    res.status(500).json({ error: message });
  }
});

export default readingsRouter;
